Add basic "Upload File" page
zooniverse/PRN-maps pull request #16
Opened 2019-03-08 18:39 UTC by shaunanoordin

## PR Overview

This PR adds a form for _(theoretically authenticated)_ to upload data files _(heatmap layers)_ to an endpoint. Closes #7 ; check that issue for full requirement details/discussion.

Goals:
- [ ] user must be able to submit their files (CSV? JSON?) to an API endpoint.
- [ ] in the submission process, user must also be able to add the layer's _metadata_ via a JSON text string.

Extended Goals:
- [ ] said user must be authenticated. (⚠️ if not tackled in this PR, then definitely in a later authentication PR)

### Status

WIP

At the moment (Fri 8 Mar), there is _no endpoint_ to submit the files to. Details for this will be discussed with @camallen

2019-03-11 09:22 UTC, eatyourgreens requested changes
Looks good to me. Just a couple of comments on the form tag and the files label.

Any strong opinions as to whether the URL should be https://prn-maps.planetaryresponsenetwork.org/maps/upload.html or https://prn-maps.planetaryresponsenetwork.org/uploads ?

2019-03-11 09:22 UTC, eatyourgreens commented on maps/upload.html
> +  <form>
The API endpoint hasn't been set up yet but I'd add `method=post` and `action=https://maps-api.planetaryresponsenetwork.org/uploads` to stub this out.

2019-03-11 09:22 UTC, eatyourgreens commented on maps/upload.html
> +      <label>Files</label>
This label isn't linked to a form input. It should either wrap the input, or be linked using `htmlFor` on the label and `id` on the input.

2019-03-11 09:24 UTC, eatyourgreens commented
Re. authentication: if the form's action URL requires basic auth, then the browser should prompt for a username and password before submitting the form. So I think we won't need to worry about that.

2019-03-11 09:26 UTC, eatyourgreens commented
One other thing I forgot: once the API is set up, then the file input will need a name that matches the variable name expected by the API.

2019-03-12 16:27 UTC, shaunanoordin commented
## PR Update

- A basic JSON metadata editor (which validates whether a JSON string is valid or not) has been added, though this may later be replaced by simply letting the users submit a JSON metadata file alongside the data-content files
- the HTML form has been hooked up, in preparation for form submission.
  - We're waiting for the API endpoint to test this.
  - Note: the currently intended method for submitting the data is via a basic `HTML <form>`, though if we want to improve on that I'll hook the upload process to the API.js, as in PR #18 

![Screen Shot 2019-03-12 at 15 50 33](https://user-images.githubusercontent.com/13952701/54216394-799a5a80-44e1-11e9-8587-5e8d1cf9467a.png)

### Status

ToDo:
- [ ] Possible new field: "target layer" (a dropdown, indicating which heatmap layer these new data files are intended to be sent to.)
- [ ] Add some `onsubmit` validation checks

Waiting on:
- [ ] API endpoint to be ready
- [ ] confirmation of what kind of validation is required. (e.g. filenames must come in JSON-CSV pairs with the same filename? etc)
- [ ] Confirmation of new "target layer" field, and list of target layers?
  - By default I assume the list of heatmap layers is static and the same as the one used by the main Map.

2019-03-12 23:50 UTC, camallen commented
I've made a start on the upload API in https://github.com/zooniverse/PRN-maps-api/commit/bfeef7dd01dd77ec0fee1ba93a7f5c48100dd15f

the API is expecting the form to have layers, the form 
https://github.com/zooniverse/PRN-maps-api/blob/bfeef7dd01dd77ec0fee1ba93a7f5c48100dd15f/prn_maps/app.rb#L135

one metadata file via 
https://github.com/zooniverse/PRN-maps-api/blob/bfeef7dd01dd77ec0fee1ba93a7f5c48100dd15f/prn_maps/app.rb#L132

The form i've tested with looks like this:
``` html
<form action="//local.zooniverse.org:3000/upload/layers/test_event_name" method="post" enctype='multipart/form-data'>
    <div class="row">
      <label for="metadata">Metadata</label>
<textarea id="json_metadata" name="json_metadata">
{
  "key1": "value1",
  "key2": "value2"
}
</textarea>
      <span id="metadata-status"></span>
    </div>
    <div class="row">
      <label for="layers">Layers</label>
      <input id="layers" name="layers[]" type="file" accept=".csv" multiple>
    </div>
    <div class="row">
      <label for="metadata">Metadata</label>
      <input id="metadata" name="metadata" type="file" accept=".json">
    </div>
    <div class="row">
      <input id="submit-button" type="submit" value="Upload">
    </div>
  </form>
```

2019-03-13 21:14 UTC, shaunanoordin commented
## PR Update
- We can now select which PRN Event to upload our data to.

Testing some close-enough-to-legit data files now.

2019-03-14 16:48 UTC, shaunanoordin commented
## PR Update

- Branched rebased to master now that #18 has been merged (which now includes API.post())
- upload form improved so that _it now works_ and can properly send files to the API. (It was `<input name="layers[]">` instead of `<input name="layers">` btw)

Next up: using either the `API` or `superagent` to post the data, instead of using the standard HTML `<form>` (otherwise users will just be directed to a page with the JSON success/fail response, which won't make as much sense to them).

2019-03-14 19:28 UTC, shaunanoordin commented
## PR Update

![Screen Shot 2019-03-14 at 19 19 43](https://user-images.githubusercontent.com/13952701/54385280-24e81280-468e-11e9-82bb-6d89df355bd9.png)

PR is now complete.

- Users are now able to submit files via the upload form.
- The upload form properly informs the user of success, or error messages from the server.

The API is receiving the files successfully (though I understand that they're not being processed server-side yet, but will be soon) and I can confirm that I'm getting legit API error messages for when: 1. I didn't send the metadata file, 2. I didn't send the layers files, or 3. the metadata doesn't properly describe the layers files.

Side note: I should have made this clear earlier, but the upload form is accessible from `http://local.zooniverse.org:3735/maps/upload.html`

### Status

Ready!

2019-03-15 10:26 UTC, camallen approved these changes
LGTM

2019-03-15 10:26 UTC, camallen commented on js/upload.js
> +//const htmlMetadata = document.getElementById('metadata');
if the metadata validator / viewer isn't eing used, can we just remove these and other comments to keep the code clean?

2019-03-15 14:40 UTC, shaunanoordin commented
## PR Update
- Unused metadata code has been removed

### Status
Merging!

2019-03-15 14:41 UTC, merged

2019-03-15 14:42 UTC, shaunanoordin commented
Wait the unnecessary metadata code wasn't actually removed, yipes, let's fix that.